### ISSUE TITLE
Add proper handling of .wad files

### ISSUE THREAD

**Issue by Halamix2** [GiovanniCastellano/StuntGPEditor#1]
.wad files are renamed Worms Armageddon .DIR archives, an archive type which was extensively documented, and have existing libraries:

* https://worms2d.info/Graphics_directory
* https://sgp.halamix2.pl/wiki/File_archive
* https://gitlab.com/Syroot/Worms - read/write library in C#
* https://github.com/Halamix2/stunt_gp_formats/tree/main/python

The files inside are regular .csv files and can be easily parsed.

This change could allow editing values with different number of digits, and different size of the resulting .wad file

**Comment by GiovanniCastellano** [comment]
Sorry for the late response, i've just updated the repository and releases! It now uses the Syroot.Worms library to read/write files, so, as you said, it is now possible to modify values with no constraints.

Thank you for the suggestions btw
